### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by boyfromgermany** [mablono5/Twittercompbot#1]
It says:
Traceback (most recent call last):
  File "twittercompbot.py", line 19, in <module>
    search_results = twitter.search(q=keywords)
  File "/usr/local/lib/python2.7/dist-packages/twython/endpoints.py", line 268, in search
    return self.get('search/tweets', params=params)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 264, in get
    return self.request(endpoint, params=params, version=version)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 258, in request
    api_call=url)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 194, in _request
    retry_after=response.headers.get('X-Rate-Limit-Reset'))
twython.exceptions.TwythonAuthError: Twitter API returned a 401 (Unauthorized), Could not authenticate you.

BTW: the twitter api keys are correct, does it need some time for twitter to unlock them ?

**Comment by mablono5** [comment]
Theres a chance that the keys haven't been put in in the right order. 

 Consumer Key (API Key) - APP_KEY
Consumer Secret (API Secret) - APP_SECRET
 Access Token - OAUTH_TOKEN
Access Token Secret - OAUTH_TOKEN_SECRET

Double check the input you have used in which order
